knative:
  operators:
    - kind: "KnativeServing"
      name: "knative-serving"
      namespace: "knative-serving"
    - kind: "KnativeEventing"
      name: "knative-eventing"
      namespace: "knative-eventing"
    - kind: "KnativeKafka"
      name: "knative-kafka"
      namespace: "knative-eventing"
  kafkaSource:
    bootstrapserver: "xray-cluster-kafka-bootstrap.xraylab-1.svc:9092"
